# Generated by Django 4.2 on 2024-01-15 17:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Company',
            fields=[
                ('comp_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('compname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('contactperson', models.CharField(max_length=150, null=True)),
                ('PAN', models.CharField(max_length=45, null=True)),
                ('GST', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'kuberji_company',
            },
        ),
       
        
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('site_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('sitename', models.CharField(max_length=100)),
                ('add1', models.CharField(blank=True, max_length=100, null=True)),
                ('add2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=45, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(max_length=45, null=True)),
                ('phone', models.CharField(max_length=45, null=True)),
                ('contactperson', models.CharField(max_length=150, null=True)),
                ('Isactive', models.BooleanField()),
                ('compid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'db_table': 'kuberji_site',
            },
        ),
       
        
        
    ]
