# Generated by Django 4.2 on 2024-01-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
    ]
