# Generated by Django 4.2 on 2024-01-20 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activity_attandancetype_declareholidays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandance',
            name='typid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.attandancetype'),
        ),
    ]
