# Generated by Django 4.2 on 2024-01-20 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_attandance_typid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityqty',
            name='actid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AlterField(
            model_name='activityqty',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sites'),
        ),
        migrations.AlterField(
            model_name='attandance',
            name='supid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='detailpayroll',
            name='Plsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payrolllist'),
        ),
        migrations.AlterField(
            model_name='detailpayroll',
            name='supid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='matid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.material'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sites'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='supid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='inwardoutward',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sites'),
        ),
        migrations.AlterField(
            model_name='labourdata',
            name='actid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity'),
        ),
        migrations.AlterField(
            model_name='labourdata',
            name='siteid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sites'),
        ),
        migrations.AlterField(
            model_name='labourdata',
            name='supid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supdata', to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='supid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='leaveregister',
            name='supid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='material',
            name='groupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matgroup'),
        ),
        migrations.AlterField(
            model_name='salaryregister',
            name='supid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier'),
        ),
    ]
