# Generated by Django 5.0 on 2024-02-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_activityqty_actid_alter_activityqty_siteid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryregister',
            name='post',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='contactperson',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='add2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
