# Generated by Django 5.0 on 2024-02-09 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_salaryregister_post_alter_sites_contactperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryregister',
            name='supid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='api.supplier'),
        ),
    ]
